#pragma once
#define STEIKEMANN_MAJOR 0
#define STEIKEMANN_MINOR 0
#define STEIKEMANN_PATCH 7
#define STEIKEMANN_VERSION ((STEIKEMANN_MAJOR << (8 * 3)) + (STEIKEMANN_MINOR << (8 * 2)) + (STEIKEMANN_PATCH << (8 * 1)))
