file(READ "${CMAKE_CURRENT_SOURCE_DIR}/steikemann2d.gdextension.template" STEIKEMANN_GDEXTENSION_FILE_TEMPLATE)
set(STEIKEMANN_GDEXTENSION_FILE_CONTENT "${STEIKEMANN_GDEXTENSION_FILE_TEMPLATE}")

message(STATUS "GDExtension Version: ${STEIKEMANN_VERSION}")

string(REPLACE "$LIB_DEBUG" "libsteikemann2d_debug_${STEIKEMANN_VERSION}" STEIKEMANN_GDEXTENSION_FILE_CONTENT ${STEIKEMANN_GDEXTENSION_FILE_CONTENT})
string(REPLACE "$LIB_RELEASE" "libsteikemann2d_release_${STEIKEMANN_VERSION}" STEIKEMANN_GDEXTENSION_FILE_CONTENT ${STEIKEMANN_GDEXTENSION_FILE_CONTENT})

file(WRITE "${STEIKEMANN_GDEXTENSION_FILE}" ${STEIKEMANN_GDEXTENSION_FILE_CONTENT})
