set(STEIKEMANN_VERSION_INPUT_FILE "${CMAKE_SOURCE_DIR}/src/steikemann/version.txt")
set(STEIKEMANN_VERSION_OUTPUT_FILE "${CMAKE_BINARY_DIR}/src/steikemann/version.txt")

add_custom_command(
    OUTPUT ${STEIKEMANN_VERSION_OUTPUT_FILE}
    COMMENT "Copying version.txt to build directory"


    
    COMMAND ${CMAKE_COMMAND} -E copy ${STEIKEMANN_VERSION_INPUT_FILE} ${STEIKEMANN_VERSION_OUTPUT_FILE}
    DEPENDS ${STEIKEMANN_VERSION_INPUT_FILE}
)
add_custom_target(copy_version_file ALL DEPENDS ${STEIKEMANN_VERSION_OUTPUT_FILE})
